import { makeSpark } from "./format";
import { decorateHeadline } from "./impact";
import { packEvidence } from "./evidence";
import { SCORING_RULE_VERSION } from "./build";
import { isEntryComplete } from "./types";
import type {
  AppSnapshot,
  CatalystEvent,
  CompanyProfile,
  Headline,
  JournalEntry,
  MacroItem,
  SparkRange,
  Ticker,
} from "./types";
import { SEED_VERSION } from "./types";

const HOUR = 3600000;

function at(now: number, hours: number): string {
  return new Date(now + hours * HOUR).toISOString();
}

function sparkSet(seed: number): Record<SparkRange, number[]> {
  return {
    "1D": makeSpark(seed + 1, 78, 0.0004, 0.006),
    "1M": makeSpark(seed + 2, 22, 0.004, 0.028),
    "6M": makeSpark(seed + 3, 26, 0.012, 0.055),
    "1Y": makeSpark(seed + 4, 52, 0.008, 0.07),
  };
}

export function buildDemoSnapshot(now = Date.now()): AppSnapshot {
  const tickers: Ticker[] = [
    {
      id: "nvda",
      symbol: "NVDA",
      company: "NVIDIA Corporation",
      held: true,
      muted: false,
      lastPrice: 128.4,
      change: 2.68,
      changePct: 2.13,
      kind: "equity",
    },
    {
      id: "aapl",
      symbol: "AAPL",
      company: "Apple Inc.",
      held: true,
      muted: false,
      lastPrice: 228.15,
      change: -0.96,
      changePct: -0.42,
      kind: "equity",
    },
    {
      id: "msft",
      symbol: "MSFT",
      company: "Microsoft Corporation",
      held: false,
      muted: false,
      lastPrice: 428.9,
      change: 3.12,
      changePct: 0.73,
      kind: "equity",
    },
    {
      id: "amzn",
      symbol: "AMZN",
      company: "Amazon.com, Inc.",
      held: false,
      muted: false,
      lastPrice: 191.22,
      change: -2.44,
      changePct: -1.26,
      kind: "equity",
    },
    {
      id: "meta",
      symbol: "META",
      company: "Meta Platforms, Inc.",
      held: false,
      muted: false,
      lastPrice: 572.08,
      change: 6.41,
      changePct: 1.13,
      kind: "equity",
    },
    {
      id: "tsla",
      symbol: "TSLA",
      company: "Tesla, Inc.",
      held: false,
      muted: true,
      lastPrice: 241.77,
      change: -8.2,
      changePct: -3.28,
      kind: "equity",
    },
    {
      id: "jpm",
      symbol: "JPM",
      company: "JPMorgan Chase & Co.",
      held: true,
      muted: false,
      lastPrice: 214.55,
      change: 1.02,
      changePct: 0.48,
      kind: "equity",
    },
    {
      id: "avgo",
      symbol: "AVGO",
      company: "Broadcom Inc.",
      held: false,
      muted: false,
      lastPrice: 164.9,
      change: 3.55,
      changePct: 2.2,
      kind: "equity",
    },
    {
      id: "spy",
      symbol: "SPY",
      company: "SPDR S&P 500 ETF Trust",
      held: false,
      muted: false,
      lastPrice: 562.11,
      change: 1.84,
      changePct: 0.33,
      kind: "equity",
    },
    {
      id: "qqq",
      symbol: "QQQ",
      company: "Invesco QQQ Trust",
      held: false,
      muted: false,
      lastPrice: 481.2,
      change: 1.12,
      changePct: 0.23,
      kind: "equity",
    },
  ];

  const macros: MacroItem[] = [
    {
      id: "cpi",
      name: "Consumer Price Index",
      shortName: "CPI",
      series: "CPI-U YoY / Core",
      muted: false,
      kind: "macro",
    },
    {
      id: "fomc",
      name: "FOMC decision",
      shortName: "FOMC",
      series: "Fed funds rate",
      muted: false,
      kind: "macro",
    },
    {
      id: "nfp",
      name: "Nonfarm payrolls",
      shortName: "NFP",
      series: "Establishment survey",
      muted: false,
      kind: "macro",
    },
  ];

  const profiles: CompanyProfile[] = [
    {
      tickerId: "nvda",
      sector: "Information Technology",
      industry: "Semiconductors",
      description: "Designs GPUs and accelerated computing platforms for data centers, gaming, and automotive.",
      fetchedAt: at(now, -720),
    },
    {
      tickerId: "aapl",
      sector: "Information Technology",
      industry: "Consumer Electronics",
      description: "Designs iPhone, Mac, iPad, and wearable products, plus a high-margin services layer.",
      fetchedAt: at(now, -800),
    },
    {
      tickerId: "msft",
      sector: "Information Technology",
      industry: "Software — Infrastructure",
      description: "Cloud (Azure), productivity, and AI platform company.",
      fetchedAt: at(now, -760),
    },
    {
      tickerId: "amzn",
      sector: "Consumer Discretionary",
      industry: "Internet Retail",
      description: "E-commerce, AWS cloud infrastructure, advertising, and devices.",
      fetchedAt: at(now, -900),
    },
    {
      tickerId: "meta",
      sector: "Communication Services",
      industry: "Interactive Media",
      description: "Family of apps (Facebook, Instagram, WhatsApp) and Reality Labs.",
      fetchedAt: at(now, -640),
    },
    {
      tickerId: "tsla",
      sector: "Consumer Discretionary",
      industry: "Automobile Manufacturers",
      description: "Electric vehicles, energy storage, and autonomy software.",
      fetchedAt: at(now, -500),
    },
    {
      tickerId: "jpm",
      sector: "Financials",
      industry: "Diversified Banks",
      description: "US money-center bank: consumer, wholesale, markets, and asset management.",
      fetchedAt: at(now, -1000),
    },
    {
      tickerId: "avgo",
      sector: "Information Technology",
      industry: "Semiconductors",
      description: "Custom AI accelerators, networking silicon, and infrastructure software (VMware).",
      fetchedAt: at(now, -420),
    },
    {
      tickerId: "spy",
      sector: "ETF",
      industry: "Large-cap blend",
      description: "Tracks the S&P 500. Used here as a market beta reference, not a single-name call.",
      fetchedAt: at(now, -2000),
    },
  ];

  const events: CatalystEvent[] = [
    {
      id: "cpi-soon",
      kind: "macro",
      title: "CPI, August",
      macroId: "cpi",
      startsAt: at(now, 6.2),
      confirmed: true,
      session: "intraday",
      description:
        "Bureau of Labor Statistics release of the Consumer Price Index. Markets reprice the real-rate path within minutes of 8:30 ET. Core services and shelter remain the residual debate.",
      impact: ["high-vol", "sector"],
      consensus: [
        { metric: "CPI YoY", consensus: "2.8%", prior: "2.9%" },
        { metric: "Core CPI YoY", consensus: "3.1%", prior: "3.2%" },
        { metric: "CPI MoM", consensus: "0.2%", prior: "0.2%" },
      ],
      consensusSource: "Bloomberg survey, as of prior close",
      notify: true,
    },
    {
      id: "nvda-earn",
      kind: "earnings",
      title: "Q2 FY27 earnings",
      tickerId: "nvda",
      startsAt: at(now, 37),
      confirmed: true,
      session: "amc",
      description:
        "NVIDIA reports fiscal Q2. Focus: data-center revenue, Blackwell ramp, and gross-margin guide. Conference call 5:00 p.m. ET.",
      impact: ["high-vol", "implied-move", "after-close", "sector"],
      consensus: [
        { metric: "EPS", consensus: "$0.96", prior: "$0.81" },
        { metric: "Revenue", consensus: "$46.1B", prior: "$44.1B" },
        { metric: "Data-center revenue", consensus: "$41.2B", prior: "$39.1B" },
        { metric: "Gross margin", consensus: "75.5%", prior: "75.0%" },
      ],
      consensusSource: "FactSet, as of prior close",
      notify: true,
    },
    {
      id: "jpm-earn",
      kind: "earnings",
      title: "Q3 earnings",
      tickerId: "jpm",
      startsAt: at(now, 58),
      confirmed: true,
      session: "bmo",
      description:
        "JPMorgan reports. NII, charge-offs, and markets revenue set the tape for the rest of bank earnings week.",
      impact: ["sector", "implied-move"],
      consensus: [
        { metric: "EPS", consensus: "$4.72", prior: "$4.40" },
        { metric: "Revenue", consensus: "$43.8B", prior: "$42.4B" },
        { metric: "NII", consensus: "$23.1B", prior: "$22.9B" },
        { metric: "NCO ratio", consensus: "0.68%", prior: "0.63%" },
      ],
      consensusSource: "Bloomberg survey",
      notify: true,
    },
    {
      id: "aapl-earn",
      kind: "earnings",
      title: "Q4 FY26 earnings",
      tickerId: "aapl",
      startsAt: at(now, 130),
      confirmed: true,
      session: "amc",
      description:
        "Apple fiscal year-end. iPhone 17 sell-through, Services run-rate, and China commentary. Call 5:00 p.m. ET.",
      impact: ["high-vol", "implied-move", "after-close"],
      consensus: [
        { metric: "EPS", consensus: "$1.56", prior: "$1.40" },
        { metric: "Revenue", consensus: "$94.5B", prior: "$85.8B" },
        { metric: "iPhone revenue", consensus: "$51.2B", prior: "$46.2B" },
        { metric: "Gross margin", consensus: "46.4%", prior: "46.2%" },
      ],
      consensusSource: "FactSet",
      notify: true,
    },
    {
      id: "fomc-next",
      kind: "macro",
      title: "FOMC decision",
      macroId: "fomc",
      startsAt: at(now, 154),
      confirmed: true,
      session: "intraday",
      description:
        "Federal Open Market Committee statement at 2:00 p.m. ET, press conference 30 minutes later. Path of the funds rate and the dots, not the 25 bp print, move duration.",
      impact: ["high-vol", "sector"],
      consensus: [
        { metric: "Funds rate", consensus: "4.00–4.25%", prior: "4.25–4.50%" },
        { metric: "Cut priced", consensus: "25 bp", prior: "—" },
        { metric: "SEP 2026 dots (median)", consensus: "3.4%", prior: "3.6%" },
      ],
      consensusSource: "Fed funds futures / SEP",
      notify: true,
    },
    {
      id: "meta-earn",
      kind: "earnings",
      title: "Q3 earnings",
      tickerId: "meta",
      startsAt: at(now, 178),
      confirmed: true,
      session: "amc",
      description: "Meta reports. Ad pricing, Reality Labs loss, and 2026 capex for AI training clusters.",
      impact: ["high-vol", "after-close"],
      consensus: [
        { metric: "EPS", consensus: "$6.18", prior: "$5.16" },
        { metric: "Revenue", consensus: "$47.2B", prior: "$40.6B" },
        { metric: "Ad revenue", consensus: "$46.4B", prior: "$39.9B" },
        { metric: "Gross margin", consensus: "81.8%", prior: "81.5%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "tsla-est",
      kind: "earnings",
      title: "Q3 earnings (estimated)",
      tickerId: "tsla",
      startsAt: at(now, 220),
      confirmed: false,
      session: "amc",
      description:
        "Date inferred from Tesla’s historical reporting cadence (third Wednesday after quarter-end). No consensus pack until the company confirms.",
      impact: ["high-vol"],
      notify: false,
    },
    {
      id: "nfp-next",
      kind: "macro",
      title: "Employment situation",
      macroId: "nfp",
      startsAt: at(now, 250),
      confirmed: true,
      session: "intraday",
      description: "Payrolls, unemployment rate, and average hourly earnings. First Friday of the month, 8:30 ET.",
      impact: ["high-vol", "sector"],
      consensus: [
        { metric: "NFP", consensus: "+145k", prior: "+142k" },
        { metric: "Unemployment", consensus: "4.3%", prior: "4.3%" },
        { metric: "AHE YoY", consensus: "3.7%", prior: "3.8%" },
      ],
      consensusSource: "Bloomberg survey",
      notify: true,
    },
    {
      id: "avgo-earn",
      kind: "earnings",
      title: "Q3 FY26 earnings",
      tickerId: "avgo",
      startsAt: at(now, 82),
      confirmed: true,
      session: "amc",
      description: "Broadcom. AI ASIC backlog and VMware attach are the two numbers that reprice the name.",
      impact: ["implied-move", "after-close", "sector"],
      consensus: [
        { metric: "EPS", consensus: "$1.58", prior: "$1.42" },
        { metric: "Revenue", consensus: "$15.9B", prior: "$15.0B" },
        { metric: "Semiconductor revenue", consensus: "$9.4B", prior: "$8.4B" },
        { metric: "Gross margin", consensus: "64.0%", prior: "63.1%" },
      ],
      consensusSource: "FactSet",
      notify: true,
    },
    // Past events (for journal + ticker past + review)
    {
      id: "msft-past",
      kind: "earnings",
      title: "Q4 FY26 earnings",
      tickerId: "msft",
      startsAt: at(now, -14 * 24),
      confirmed: true,
      session: "amc",
      description: "Microsoft reported. Azure growth and AI Copilot attach were the debate.",
      impact: ["implied-move", "after-close"],
      consensus: [
        { metric: "EPS", consensus: "$3.35", prior: "$2.94" },
        { metric: "Revenue", consensus: "$68.6B", prior: "$61.9B" },
        { metric: "Azure growth", consensus: "32%", prior: "31%" },
        { metric: "Gross margin", consensus: "69.4%", prior: "69.3%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "amzn-past",
      kind: "earnings",
      title: "Q2 earnings",
      tickerId: "amzn",
      startsAt: at(now, -40 * 24),
      confirmed: true,
      session: "amc",
      description: "Amazon. AWS growth re-acceleration vs. retail operating margin.",
      impact: ["high-vol", "after-close"],
      consensus: [
        { metric: "EPS", consensus: "$1.26", prior: "$0.98" },
        { metric: "Revenue", consensus: "$159.1B", prior: "$143.3B" },
        { metric: "AWS revenue", consensus: "$30.2B", prior: "$27.5B" },
        { metric: "Gross margin", consensus: "48.9%", prior: "48.4%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "aapl-past",
      kind: "earnings",
      title: "Q3 FY26 earnings",
      tickerId: "aapl",
      startsAt: at(now, -55 * 24),
      confirmed: true,
      session: "amc",
      description: "Apple June quarter. Services and Greater China.",
      impact: ["after-close"],
      consensus: [
        { metric: "EPS", consensus: "$1.40", prior: "$1.35" },
        { metric: "Revenue", consensus: "$85.8B", prior: "$84.0B" },
        { metric: "Services", consensus: "$26.6B", prior: "$23.7B" },
        { metric: "Gross margin", consensus: "46.2%", prior: "46.3%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "meta-past",
      kind: "earnings",
      title: "Q2 earnings",
      tickerId: "meta",
      startsAt: at(now, -70 * 24),
      confirmed: true,
      session: "amc",
      description: "Meta June quarter. Ad pricing and capex guide.",
      impact: ["after-close"],
      consensus: [
        { metric: "EPS", consensus: "$5.16", prior: "$4.71" },
        { metric: "Revenue", consensus: "$42.9B", prior: "$36.5B" },
        { metric: "Ad revenue", consensus: "$42.2B", prior: "$35.6B" },
        { metric: "Gross margin", consensus: "81.5%", prior: "81.3%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "nvda-past",
      kind: "earnings",
      title: "Q1 FY27 earnings",
      tickerId: "nvda",
      startsAt: at(now, -85 * 24),
      confirmed: true,
      session: "amc",
      description: "NVIDIA May quarter. Blackwell supply and data-center.",
      impact: ["high-vol", "after-close", "sector"],
      consensus: [
        { metric: "EPS", consensus: "$0.81", prior: "$0.68" },
        { metric: "Revenue", consensus: "$44.1B", prior: "$39.3B" },
        { metric: "Data-center revenue", consensus: "$39.1B", prior: "$35.6B" },
        { metric: "Gross margin", consensus: "75.0%", prior: "73.5%" },
      ],
      consensusSource: "FactSet",
      notify: false,
    },
    {
      id: "jpm-past",
      kind: "earnings",
      title: "Q2 earnings",
      tickerId: "jpm",
      startsAt: at(now, -95 * 24),
      confirmed: true,
      session: "bmo",
      description: "JPMorgan June quarter. NII peak debate.",
      impact: ["sector"],
      consensus: [
        { metric: "EPS", consensus: "$4.40", prior: "$4.20" },
        { metric: "Revenue", consensus: "$42.4B", prior: "$41.9B" },
        { metric: "NII", consensus: "$22.9B", prior: "$22.8B" },
        { metric: "NCO ratio", consensus: "0.63%", prior: "0.58%" },
      ],
      consensusSource: "Bloomberg",
      notify: false,
    },
    {
      id: "cpi-past",
      kind: "macro",
      title: "CPI, July",
      macroId: "cpi",
      startsAt: at(now, -28 * 24),
      confirmed: true,
      session: "intraday",
      description: "July CPI. Core held sticky; rates sold off into the print then reversed.",
      impact: ["high-vol"],
      consensus: [
        { metric: "CPI YoY", consensus: "2.9%", prior: "3.0%" },
        { metric: "Core CPI YoY", consensus: "3.2%", prior: "3.3%" },
        { metric: "CPI MoM", consensus: "0.2%", prior: "0.3%" },
      ],
      consensusSource: "Bloomberg survey",
      notify: false,
    },
    {
      id: "spy-event",
      kind: "product",
      title: "Quad witching",
      tickerId: "spy",
      startsAt: at(now, -7 * 24),
      confirmed: true,
      session: "intraday",
      description: "September expiration. Not a fundamental catalyst — a positioning event. Logged to keep the tape honest.",
      impact: ["high-vol"],
      notify: false,
      printMovePct: -0.42,
    },
  ];

  const rawHeadlines: Headline[] = [
    {
      id: "h1",
      tickerId: "nvda",
      title: "Morgan Stanley raises NVDA price target to $220 on Blackwell ramp",
      source: "Morgan Stanley",
      publishedAt: at(now, -2),
      summary: "PT lifted from $185. Street is still catching up to CoWoS allocation in 4Q.",
    },
    {
      id: "h2",
      tickerId: "nvda",
      title: "TSMC said to raise CoWoS allocation for Blackwell in 4Q",
      source: "Reuters",
      publishedAt: at(now, -5),
      summary: "Supply-chain sources say extra CoWoS capacity is earmarked for NVDA, not competitors.",
    },
    {
      id: "h3",
      tickerId: "nvda",
      title: "Cloud hyperscalers lock multi-year GPU supply, filings show",
      source: "The Information",
      publishedAt: at(now, -18),
    },
    {
      id: "h4",
      tickerId: "aapl",
      title: "Apple announces expanded iPhone 17 production after preorders beat plan",
      source: "Company",
      publishedAt: at(now, -3),
      summary: "Cupertino is adding a second assembly line in India. Hardware mix, not Services, is the swing.",
    },
    {
      id: "h5",
      tickerId: "aapl",
      title: "iPhone 17 preorders track ahead of 16 in the first 72 hours, channel checks",
      source: "Wedbush",
      publishedAt: at(now, -11),
    },
    {
      id: "h6",
      tickerId: "msft",
      title: "Goldman upgrades MSFT to Overweight from Neutral, $560 target",
      source: "Goldman Sachs",
      publishedAt: at(now, -6),
      summary: "Azure AI capacity remains the constraint, not demand. Rating change is the flow event.",
    },
    {
      id: "h7",
      tickerId: "amzn",
      title: "Wedbush initiates AMZN coverage at Outperform, $250 price target",
      source: "Wedbush",
      publishedAt: at(now, -10),
    },
    {
      id: "h8",
      tickerId: "meta",
      title: "Meta announces $40B buyback and raises 2026 capex guide",
      source: "Company",
      publishedAt: at(now, -4),
      summary: "Buyback is the floor. Capex raise is the tell on Reels and AI infra.",
    },
    {
      id: "h9",
      tickerId: "jpm",
      title: "JPM 8-K: NII guide cut $1.2B on deposit mix",
      source: "SEC",
      publishedAt: at(now, -8),
      summary: "The only number that matters this print is now lower. Primary filing.",
    },
    {
      id: "h10",
      tickerId: "tsla",
      title: "Tesla files 8-K: unsupervised robotaxi timeline delayed to 2027",
      source: "SEC",
      publishedAt: at(now, -1),
      summary: "Deliveries were never the swing. This 8-K is.",
    },
    {
      id: "h11",
      tickerId: "avgo",
      title: "Broadcom announces custom AI ASIC design win with a second hyperscaler",
      source: "Company",
      publishedAt: at(now, -1.5),
    },
    {
      id: "h12",
      macroId: "cpi",
      title: "Shelter still the last sticky piece of core services",
      source: "BLS / FT",
      publishedAt: at(now, -4),
    },
    {
      id: "h13",
      macroId: "cpi",
      title: "A 0.1-point miss on core would reprice two 2026 cuts",
      source: "Goldman desk note",
      publishedAt: at(now, -2),
    },
    {
      id: "h14",
      macroId: "fomc",
      title: "Committee is data-dependent in public, path-dependent in the dots",
      source: "Fed watch",
      publishedAt: at(now, -20),
    },
    {
      id: "h15",
      tickerId: "spy",
      title: "These 7 stocks to buy ahead of CPI — here's why",
      source: "Motley Fool",
      publishedAt: at(now, -1),
    },
    {
      id: "h16",
      tickerId: "nvda",
      title: "Implied move into print: 8.4%, below the 4-quarter average",
      source: "Bloomberg",
      publishedAt: at(now, -3),
    },
    {
      id: "h17",
      tickerId: "aapl",
      title: "Services growth still the margin offset if hardware mix disappoints",
      source: "Barron's",
      publishedAt: at(now, -30),
    },
    {
      id: "h18",
      tickerId: "avgo",
      title: "Custom AI silicon backlog extends through 2027, supply chain says",
      source: "Nikkei",
      publishedAt: at(now, -8),
    },
  ];

  const headlines: Headline[] = rawHeadlines.map((h) => {
    const deco = decorateHeadline(h);
    return { ...h, ...deco, scoredBy: "fixture" as const, origin: "fixture" as const, firstSeenAt: h.publishedAt };
  });

  const entries: JournalEntry[] = [
    // Quick note on upcoming NVDA — incomplete (no conviction, no invalidation)
    {
      id: "e-nvda-quick",
      eventId: "nvda-earn",
      text: "Blackwell revenue should clear $41B. Street is still anchored to Hopper run-rate.",
      sentiment: "bullish",
      direction: "up",
      conviction: null,
      reasoning: "Blackwell revenue should clear $41B. Street is still anchored to Hopper run-rate.",
      invalidation: null,
      updatedAt: at(now, -2),
    },
    // Incomplete: conviction missing on AVGO
    {
      id: "e-avgo-inc",
      eventId: "avgo-earn",
      text: "AI ASIC mix should hold gross margin. Need to write the invalidation.",
      sentiment: "bullish",
      direction: "up",
      conviction: null,
      reasoning: "AI ASIC mix should hold gross margin above 63.5% even if VMware is in-line.",
      invalidation: null,
      updatedAt: at(now, -1),
    },
    // Incomplete: direction missing on FOMC (blank-ish but has text)
    {
      id: "e-fomc-inc",
      eventId: "fomc-next",
      text: "Dots matter more than the 25 bp. Not ready to pick a direction on SPY from this.",
      sentiment: "none",
      direction: null,
      conviction: 2,
      reasoning: "Dots matter more than the 25 bp. Not ready to pick a direction on SPY from this.",
      invalidation: "A hawkish skip that lifts the 2026 median above 3.9%.",
      updatedAt: at(now, -3),
    },
    // Scored: 5 of 7 called. Spec: "5 of 7 scored calls"
    {
      id: "e-msft",
      eventId: "msft-past",
      text: "Azure holds 30%+; Copilot is mix, not the print.",
      sentiment: "bullish",
      direction: "up",
      conviction: 4,
      reasoning:
        "Azure holds 30%+ even if guidance is conservative. Capacity is the bottleneck, so a beat on commercial is likely and the stock still trades the growth print.",
      invalidation: "Azure growth guided to 28% or below, or capex cut that signals demand, not supply.",
      updatedAt: at(now, -14 * 24 - 6),
      actualDirection: "up",
      actualMovePct: 3.8,
      actualMoveDate: at(now, -13 * 24),
      actualFigure: "Azure +33%. You wrote: Azure growth guided to 28% or below. It came in at 33%.",
    },
    {
      id: "e-amzn",
      eventId: "amzn-past",
      text: "AWS reaccelerates; retail margin is noise.",
      sentiment: "bullish",
      direction: "up",
      conviction: 3,
      reasoning:
        "AWS should print a 12-handle on growth. Retail opex is a 2025 story. The stock still trades AWS first.",
      invalidation: "AWS growth below 11%, or capex guide that implies idle capacity.",
      updatedAt: at(now, -40 * 24 - 8),
      actualDirection: "down",
      actualMovePct: -5.4,
      actualMoveDate: at(now, -39 * 24),
      actualFigure: "AWS +10.8%. You wrote: AWS growth below 11%. It came in at 10.8%.",
    },
    {
      id: "e-aapl",
      eventId: "aapl-past",
      text: "Services carries the quarter; China is already in the price.",
      sentiment: "bullish",
      direction: "up",
      conviction: 3,
      reasoning:
        "Services run-rate above $26B offsets a soft Greater China hardware line. Multiple is already discounted for China.",
      invalidation: "Services below $25.5B or gross margin guided under 45.5%.",
      updatedAt: at(now, -55 * 24 - 5),
      actualDirection: "up",
      actualMovePct: 2.1,
      actualMoveDate: at(now, -54 * 24),
      actualFigure: "Services $26.6B, GM 46.2%. You wrote: Services below $25.5B. It came in at $26.6B.",
    },
    {
      id: "e-meta",
      eventId: "meta-past",
      text: "Ad pricing + Reels. Capex is known.",
      sentiment: "bullish",
      direction: "up",
      conviction: 5,
      reasoning:
        "Ad pricing is inflecting with Reels. Capex guide will be large and already teed up. The print is about family-of-apps revenue.",
      invalidation: "Family-of-apps revenue miss or 2026 capex taken above $70B without a revenue raise.",
      updatedAt: at(now, -70 * 24 - 4),
      actualDirection: "up",
      actualMovePct: 6.2,
      actualMoveDate: at(now, -69 * 24),
      actualFigure: "Revenue $42.9B vs $42.3B street. You wrote: FoA revenue miss. It beat.",
    },
    {
      id: "e-nvda-past",
      eventId: "nvda-past",
      text: "Data-center $39B. Margin holds 75.",
      sentiment: "bullish",
      direction: "up",
      conviction: 4,
      reasoning:
        "Blackwell starts to show up in mix. Data-center clears $39B and they hold a 75 handle on gross margin.",
      invalidation: "Gross-margin guide below 73%.",
      updatedAt: at(now, -85 * 24 - 5),
      actualDirection: "up",
      actualMovePct: 4.4,
      actualMoveDate: at(now, -84 * 24),
      actualFigure: "You wrote: margin guide below 73%. It came in at 75.0%.",
    },
    {
      id: "e-jpm",
      eventId: "jpm-past",
      text: "NII has peaked. Fade the print.",
      sentiment: "bearish",
      direction: "down",
      conviction: 2,
      reasoning:
        "NII has peaked with the cut cycle starting. A clean EPS beat will not hold if NII is guided sideways.",
      invalidation: "NII guided up, or markets revenue surprise above $7B that funds the year.",
      updatedAt: at(now, -95 * 24 - 10),
      actualDirection: "up",
      actualMovePct: 1.6,
      actualMoveDate: at(now, -94 * 24),
      actualFigure: "NII $22.9B, guided stable. You wrote: NII guided up. It was stable, stock still bid.",
    },
    {
      id: "e-cpi-past",
      eventId: "cpi-past",
      text: "Core holds 3.2. Duration sells the print.",
      sentiment: "bearish",
      direction: "down",
      conviction: 3,
      reasoning:
        "Core CPI stays at 3.2 with shelter lagging. Front-end rates sell the print; risk assets follow for a session.",
      invalidation: "Core at 3.0 or below, which would pull two more 2026 cuts into the tape.",
      updatedAt: at(now, -28 * 24 - 12),
      actualDirection: "down",
      actualMovePct: -0.9,
      actualMoveDate: at(now, -28 * 24 + 8),
      actualFigure: "Core 3.2% on the nose. You wrote: core at 3.0 or below. It held 3.2%.",
    },
    // Quick note on past SPY with no full entry — still incomplete, shows in pending
    {
      id: "e-spy-note",
      eventId: "spy-event",
      text: "Positioning event. Fade the close, don't invent a fundamental view.",
      sentiment: "none",
      direction: "flat",
      conviction: 2,
      reasoning: "Quad witching is a positioning event. Expect a mean-reverting session, not a trend day.",
      invalidation: "A 1%+ directional close that holds into the next open.",
      updatedAt: at(now, -8 * 24),
    },
  ];

  const stamped: JournalEntry[] = entries.map((e) => {
    if (!isEntryComplete(e) || e.actualDirection == null) return e;
    const ev = events.find((x) => x.id === e.eventId);
    const related = headlines.filter((h) =>
      ev?.tickerId ? h.tickerId === ev.tickerId : Boolean(ev?.macroId && h.macroId === ev.macroId),
    );
    return {
      ...e,
      lockedAt: e.updatedAt,
      evidenceSnapshot: packEvidence(related.slice(0, 4)),
      scoringRuleVersion: e.id === "e-jpm" ? undefined : SCORING_RULE_VERSION,
      callTarget: ev?.kind === "macro" ? "qqq" : e.callTarget,
    };
  });

  const sparks: AppSnapshot["sparks"] = {};
  for (const t of tickers) {
    sparks[t.id] = sparkSet(t.symbol.charCodeAt(0) * 100 + t.symbol.charCodeAt(1));
  }

  const earningsHistory: AppSnapshot["earningsHistory"] = {
    nvda: [
      { period: "Q1 FY27", actual: 0.81, estimate: 0.76, surprisePct: 6.6 },
      { period: "Q4 FY26", actual: 0.89, estimate: 0.85, surprisePct: 4.7 },
      { period: "Q3 FY26", actual: 0.81, estimate: 0.75, surprisePct: 8.0 },
      { period: "Q2 FY26", actual: 0.68, estimate: 0.64, surprisePct: 6.3 },
    ],
    aapl: [
      { period: "Q3 FY26", actual: 1.4, estimate: 1.35, surprisePct: 3.7 },
      { period: "Q2 FY26", actual: 1.65, estimate: 1.62, surprisePct: 1.9 },
      { period: "Q1 FY26", actual: 2.4, estimate: 2.35, surprisePct: 2.1 },
      { period: "Q4 FY25", actual: 1.64, estimate: 1.6, surprisePct: 2.5 },
    ],
    msft: [
      { period: "Q4 FY26", actual: 3.65, estimate: 3.35, surprisePct: 9.0 },
      { period: "Q3 FY26", actual: 3.46, estimate: 3.22, surprisePct: 7.5 },
      { period: "Q2 FY26", actual: 3.23, estimate: 3.1, surprisePct: 4.2 },
      { period: "Q1 FY26", actual: 3.3, estimate: 3.1, surprisePct: 6.5 },
    ],
    jpm: [
      { period: "Q2", actual: 4.63, estimate: 4.4, surprisePct: 5.2 },
      { period: "Q1", actual: 4.61, estimate: 4.49, surprisePct: 2.7 },
      { period: "Q4", actual: 4.81, estimate: 4.1, surprisePct: 17.3 },
      { period: "Q3", actual: 4.37, estimate: 3.99, surprisePct: 9.5 },
    ],
    avgo: [
      { period: "Q2 FY26", actual: 1.42, estimate: 1.37, surprisePct: 3.6 },
      { period: "Q1 FY26", actual: 1.4, estimate: 1.32, surprisePct: 6.1 },
      { period: "Q4 FY25", actual: 1.42, estimate: 1.39, surprisePct: 2.2 },
      { period: "Q3 FY25", actual: 1.24, estimate: 1.2, surprisePct: 3.3 },
    ],
    meta: [
      { period: "Q2", actual: 5.16, estimate: 4.97, surprisePct: 3.8 },
      { period: "Q1", actual: 6.43, estimate: 4.96, surprisePct: 29.6 },
      { period: "Q4", actual: 8.02, estimate: 6.76, surprisePct: 18.6 },
      { period: "Q3", actual: 6.03, estimate: 5.25, surprisePct: 14.9 },
    ],
    amzn: [
      { period: "Q2", actual: 1.68, estimate: 1.32, surprisePct: 27.3 },
      { period: "Q1", actual: 1.59, estimate: 1.37, surprisePct: 16.1 },
      { period: "Q4", actual: 1.86, estimate: 1.49, surprisePct: 24.8 },
      { period: "Q3", actual: 1.43, estimate: 1.14, surprisePct: 25.4 },
    ],
    tsla: [
      { period: "Q2", actual: 0.4, estimate: 0.53, surprisePct: -24.5 },
      { period: "Q1", actual: 0.27, estimate: 0.42, surprisePct: -35.7 },
      { period: "Q4", actual: 0.73, estimate: 0.76, surprisePct: -3.9 },
      { period: "Q3", actual: 0.72, estimate: 0.58, surprisePct: 24.1 },
    ],
  };

  const recommendations: AppSnapshot["recommendations"] = {
    nvda: { buy: 48, hold: 6, sell: 1, period: "2026-09" },
    aapl: { buy: 32, hold: 14, sell: 3, period: "2026-09" },
    msft: { buy: 41, hold: 8, sell: 0, period: "2026-09" },
    jpm: { buy: 18, hold: 9, sell: 2, period: "2026-09" },
    avgo: { buy: 36, hold: 5, sell: 1, period: "2026-09" },
    meta: { buy: 44, hold: 7, sell: 2, period: "2026-09" },
    amzn: { buy: 47, hold: 4, sell: 0, period: "2026-09" },
    tsla: { buy: 22, hold: 16, sell: 11, period: "2026-09" },
  };

  return {
    seedVersion: SEED_VERSION,
    demoMode: true,
    emptySeed: false,
    theme: "dark",
    notifyLead: "both",
    dataSource: "fixture",
    liveKeys: { finnhub: "", alphaVantage: "", newsapi: "" },
    tickers,
    macros,
    profiles,
    events,
    headlines,
    entries: stamped,
    quotes: tickers.map((t) => {
      const prev = Number((t.lastPrice - t.change).toFixed(2));
      const high = Number((Math.max(t.lastPrice, prev) + Math.abs(t.change) * 0.35).toFixed(2));
      const low = Number((Math.min(t.lastPrice, prev) - Math.abs(t.change) * 0.22).toFixed(2));
      const open = Number((prev + t.change * 0.18).toFixed(2));
      return {
        tickerId: t.id,
        lastPrice: t.lastPrice,
        change: t.change,
        changePct: t.changePct,
        fetchedAt: at(now, -0.2),
        dayHigh: high,
        dayLow: low,
        dayOpen: open,
        prevClose: prev,
      };
    }),
    sparks,
    earningsHistory,
    recommendations,
    tape: {
      nvda: { tickerId: "nvda", marketCap: 3_140_000, pe: 48.2, week52High: 153.13, week52Low: 86.62, target: 180, fetchedAt: at(now, -2) },
      aapl: { tickerId: "aapl", marketCap: 3_420_000, pe: 33.1, week52High: 260.1, week52Low: 169.21, target: 246, fetchedAt: at(now, -2) },
      msft: { tickerId: "msft", marketCap: 3_190_000, pe: 36.4, week52High: 468.35, week52Low: 344.79, target: 510, fetchedAt: at(now, -2) },
      amzn: { tickerId: "amzn", marketCap: 2_010_000, pe: 37.8, week52High: 242.52, week52Low: 151.61, target: 230, fetchedAt: at(now, -2) },
      meta: { tickerId: "meta", marketCap: 1_450_000, pe: 27.6, week52High: 602.95, week52Low: 442.65, target: 640, fetchedAt: at(now, -2) },
      tsla: { tickerId: "tsla", marketCap: 770_000, pe: 148, week52High: 488.54, week52Low: 182.0, target: 268, fetchedAt: at(now, -2) },
      jpm: { tickerId: "jpm", marketCap: 590_000, pe: 13.8, week52High: 225.98, week52Low: 190.0, target: 230, fetchedAt: at(now, -2) },
      avgo: { tickerId: "avgo", marketCap: 770_000, pe: 52.4, week52High: 192.0, week52Low: 120.0, target: 185, fetchedAt: at(now, -2) },
      spy: { tickerId: "spy", marketCap: 620_000, pe: 24.1, week52High: 566.0, week52Low: 481.0, fetchedAt: at(now, -2) },
      qqq: { tickerId: "qqq", marketCap: 280_000, pe: 28.4, week52High: 505.0, week52Low: 402.0, fetchedAt: at(now, -2) },
    },
    macroPrints: {
      cpi: { macroId: "cpi", value: "3.0% YoY", prior: "2.9%", asOf: at(now, -28 * 24), source: "BLS" },
      fomc: { macroId: "fomc", value: "4.50%", prior: "4.50%", asOf: at(now, -40 * 24), source: "Fed" },
      nfp: { macroId: "nfp", value: "+142k", prior: "+147k", asOf: at(now, -21 * 24), source: "BLS" },
    },
  };
}

export function buildEmptySnapshot(now = Date.now()): AppSnapshot {
  const demo = buildDemoSnapshot(now);
  return {
    ...demo,
    emptySeed: true,
    tickers: [],
    macros: [],
    events: [],
    headlines: [],
    entries: [],
    quotes: [],
    sparks: {},
    profiles: demo.profiles,
    earningsHistory: {},
    recommendations: {},
    tape: {},
    macroPrints: {},
  };
}

export const EMPTY_COPY = {
  nowTitle: "Nothing to call yet",
  nowBody:
    "Follow one name. Catalyst will put the next print here — and wait for your call before it ever scores you.",
  timelineTitle: "Your timeline is empty",
  timelineBody:
    "Follow a ticker or a macro release and Catalyst will line up the next events, nearest first.",
  watchlistTitle: "Follow a name",
  watchlistBody: "Search a US-listed equity or ETF, or follow CPI and FOMC as first-class events.",
  reviewTitle: "No scored calls yet",
  reviewBody:
    "A call scores the session after the print — only if direction, conviction, why, and invalidation are all set.",
};
