import type { SearchHit } from "./types";

/** US-listed equities and ETFs the Watchlist search can resolve. */
export const SEARCH_UNIVERSE: SearchHit[] = [
  { symbol: "AAPL", company: "Apple Inc.", type: "equity" },
  { symbol: "MSFT", company: "Microsoft Corporation", type: "equity" },
  { symbol: "NVDA", company: "NVIDIA Corporation", type: "equity" },
  { symbol: "AMZN", company: "Amazon.com, Inc.", type: "equity" },
  { symbol: "META", company: "Meta Platforms, Inc.", type: "equity" },
  { symbol: "GOOGL", company: "Alphabet Inc. Class A", type: "equity" },
  { symbol: "TSLA", company: "Tesla, Inc.", type: "equity" },
  { symbol: "AVGO", company: "Broadcom Inc.", type: "equity" },
  { symbol: "JPM", company: "JPMorgan Chase & Co.", type: "equity" },
  { symbol: "V", company: "Visa Inc.", type: "equity" },
  { symbol: "UNH", company: "UnitedHealth Group", type: "equity" },
  { symbol: "XOM", company: "Exxon Mobil Corporation", type: "equity" },
  { symbol: "LLY", company: "Eli Lilly and Company", type: "equity" },
  { symbol: "JNJ", company: "Johnson & Johnson", type: "equity" },
  { symbol: "WMT", company: "Walmart Inc.", type: "equity" },
  { symbol: "MA", company: "Mastercard Incorporated", type: "equity" },
  { symbol: "PG", company: "Procter & Gamble", type: "equity" },
  { symbol: "COST", company: "Costco Wholesale", type: "equity" },
  { symbol: "HD", company: "The Home Depot, Inc.", type: "equity" },
  { symbol: "ORCL", company: "Oracle Corporation", type: "equity" },
  { symbol: "AMD", company: "Advanced Micro Devices", type: "equity" },
  { symbol: "NFLX", company: "Netflix, Inc.", type: "equity" },
  { symbol: "CRM", company: "Salesforce, Inc.", type: "equity" },
  { symbol: "BAC", company: "Bank of America", type: "equity" },
  { symbol: "KO", company: "The Coca-Cola Company", type: "equity" },
  { symbol: "DIS", company: "The Walt Disney Company", type: "equity" },
  { symbol: "INTC", company: "Intel Corporation", type: "equity" },
  { symbol: "QCOM", company: "QUALCOMM Incorporated", type: "equity" },
  { symbol: "AMAT", company: "Applied Materials", type: "equity" },
  { symbol: "MU", company: "Micron Technology", type: "equity" },
  { symbol: "SMCI", company: "Super Micro Computer", type: "equity" },
  { symbol: "ARM", company: "Arm Holdings plc", type: "equity" },
  { symbol: "ASML", company: "ASML Holding N.V.", type: "equity" },
  { symbol: "TSM", company: "Taiwan Semiconductor", type: "equity" },
  { symbol: "SPY", company: "SPDR S&P 500 ETF Trust", type: "etf" },
  { symbol: "QQQ", company: "Invesco QQQ Trust", type: "etf" },
  { symbol: "IWM", company: "iShares Russell 2000 ETF", type: "etf" },
  { symbol: "XLF", company: "Financial Select Sector SPDR", type: "etf" },
  { symbol: "XLK", company: "Technology Select Sector SPDR", type: "etf" },
  { symbol: "GLD", company: "SPDR Gold Shares", type: "etf" },
  { symbol: "TLT", company: "iShares 20+ Year Treasury", type: "etf" },
];
