// Bundles Cloud Code (src/main.ts + the C67 modules it imports) into dist/main.js for Back4App.
// Target is the Cloud Code runtime measured in §2: Node 19.9.0, CommonJS.
import { build } from "esbuild";
import path from "node:path";
import { fileURLToPath } from "node:url";

const cloudDir = path.dirname(fileURLToPath(import.meta.url));
const result = await build({
  absWorkingDir: cloudDir,
  entryPoints: ["src/main.ts"],
  outfile: "dist/main.js",
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node19",
  legalComments: "none",
  metafile: true,
  banner: { js: "// Catalyst Cloud Code. Generated by cloud/build.mjs from cloud/src/main.ts; do not edit." },
  logLevel: "warning",
});
const inputs = Object.keys(result.metafile.inputs).filter((f) => f.includes("lib/catalyst/")).map((f) => path.basename(f));
const bytes = result.metafile.outputs["dist/main.js"].bytes;
console.log(`built dist/main.js (${bytes} bytes) with C67 modules: ${inputs.join(", ")}`);
